### ISSUE TITLE
yolov8在3568模型推理出错

### ISSUE THREAD

**Issue by AntyRia** [airockchip/rknn_model_zoo#102]
我根据你们提供的yolov8的onnx模型，成功运行了导出脚本，获得了rknn模型，当我使用类似如下的语句在rk3568设备上，进行python推理时遇到问题:
`python yolov8.py --model_path ../model/yolov8.rknn --target rk3568 --img_save`
首先遇到问题：
`ModuleNotFoundError: No module named 'rknn'`,
我将 `/rknn_model_zoo/py_utils/rknn_executor.py`中的 `# from rknn.api import RKNN`修改为`from rknnlite.api import RKNNLite`并安装了相关包，此时推理出错
报错：
`--> Init runtime environment
E RKNNAPI: rknn_init,  driver open fail!  ret = -12(ERROR_NOT_SUPPORTED)!
E Catch exception when init runtime!
*************************
None devices connected.
*************************
E []
E Traceback (most recent call last):
  File "/home/cat/miniconda3/envs/yolov8/lib/python3.8/site-packages/rknnlite/api/rknn_lite.py", line 148, in init_runtime
    self.rknn_runtime.build_graph(self.rknn_data, self.load_model_in_npu)
  File "rknnlite/api/rknn_runtime.py", line 919, in rknnlite.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_DEVICE_UNAVAILABLE

Init runtime environment failed
`
想问问该怎么解决，有没有人有在板端的推理样例

**Comment by AntyRia** [comment]
请问还有人活着吗

**Comment by pkuma** [comment]
参考example啊，里面不是有例子吗，我跑没什么问题
