### ISSUE TITLE
The input[0] need 4dims input, but 3dims input buffer feed.

### ISSUE THREAD

**Issue by WuJalil** [airockchip/rknn_model_zoo#105]
Hi guys.
I'm currently using **Orange Pi 5 Plus** and i'm trying to deploy a yolov8 model using the **NPU**.
after facing so many 'input shape' error **when converting the model from onnx to rknn**, some how i managed to convert it though when i try to run yolov8.py with the exported model as shown in this guid [https://github.com/airockchip/rknn_model_zoo/tree/main/examples/yolov8](url) this error show up!!

`
$ python3 yolov8.py --model_path yolov8n.rknn --target RK3588 --img_show
`

The error:

```
--> Init runtime environment
I RKNN: [21:22:47.530] RKNN Runtime Information: librknnrt version: 1.5.2 (c6b7b351a@2023-08-23T15:28:22)
I RKNN: [21:22:47.530] RKNN Driver Information: version: 0.9.3
I RKNN: [21:22:47.531] RKNN Model Information: version: 6, toolkit version: 2.0.0b0+9bab5682(compiler version: 2.0.0b0 (35a6907d79@2024-03-24T02:34:11)), target: RKNPU v2, target platform: rk3588, framework name: ONNX, framework layout: NCHW, model inference type: static_shape
W RKNN: [21:22:47.531] RKNN Model version: 2.0.0 not match with rknn runtime version: 1.5.2
W RKNN: [21:22:47.542] query RKNN_QUERY_INPUT_DYNAMIC_RANGE error, rknn model is static shape type, please export rknn with dynamic_shapes
W Query dynamic range failed. Ret code: RKNN_ERR_MODEL_INVALID. (If it is a static shape RKNN model, please ignore the above warning message.)
done
Model-yolov8n.rknn is rknn model, starting val
E Catch exception when setting inputs.
E Traceback (most recent call last):
  File "/home/orangepi/.local/lib/python3.8/site-packages/rknnlite/api/rknn_lite.py", line 200, in inference
    self.rknn_runtime.set_inputs(inputs, data_type, data_format, inputs_pass_through=inputs_pass_through)
  File "rknnlite/api/rknn_runtime.py", line 1067, in rknnlite.api.rknn_runtime.RKNNRuntime.set_inputs
Exception: The input[0] need 4dims input, but 3dims input buffer feed.

Traceback (most recent call last):
  File "yolov8.py", line 269, in <module>
    boxes, classes, scores = post_process(outputs)
  File "yolov8.py", line 126, in post_process
    pair_per_branch = len(input_data)//defualt_branch
```

any answer would be appreciated  !!

**Comment by agualbbus** [comment]
Same issue!

**Comment by agualbbus** [comment]
adding a batch dimension with `np.expand_dims(img, axis=0)`  before inference solve the issue on my python script.

**Comment by WuJalil** [comment]
> adding a batch dimension with `np.expand_dims(img, axis=0)` before inference solve the issue on my python script.

yes. it's worked. thansks.

**Comment by chang50961471** [comment]
> np.expand_dims(img, axis=0)

Hello, where do I need to add it
