### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by nerbivol** [airockchip/rknn_model_zoo#114]
I executed the following command:

```bash
orangepi@orangepi5b:~/rknn_model_zoo/examples/yolov8/python$ python3 yolov8.py --model_path ../model/yolov8s.rknn --target rk3588 --img_show
```

After running the command, the output showed:

```
--> Init runtime environment
I RKNN: [18:43:51.326] RKNN Runtime Information: librknnrt version: 1.5.2 (c6b7b351a@2023-08-23T15:28:22)
I RKNN: [18:43:51.326] RKNN Driver Information: version: 0.9.3
I RKNN: [18:43:51.327] RKNN Model Information: version: 6, toolkit version: 1.5.2+b642f30c(compiler version: 1.5.2 (c6b7b351a@2023-08-23T15:34:44)), target: RKNPU v2, target platform: rk3588, framework name: ONNX, framework layout: NCHW, model inference type: static_shape
W RKNN: [18:43:51.375] query RKNN_QUERY_INPUT_DYNAMIC_RANGE error, rknn model is static shape type, please export rknn with dynamic_shapes
W Query dynamic range failed. Ret code: RKNN_ERR_MODEL_INVALID. (If it is a static shape RKNN model, please ignore the above warning message.)
done
Model-../model/yolov8s.rknn is rknn model, starting val
E Catch exception when setting inputs.
E Traceback (most recent call last):
  File "/home/orangepi/.local/lib/python3.10/site-packages/rknnlite/api/rknn_lite.py", line 200, in inference
    self.rknn_runtime.set_inputs(inputs, data_type, data_format, inputs_pass_through=inputs_pass_through)
  File "rknnlite/api/rknn_runtime.py", line 1067, in rknnlite.api.rknn_runtime.RKNNRuntime.set_inputs
Exception: The input[0] need 4dims input, but 3dims input buffer feed.

Traceback (most recent call last):
  File "/home/orangepi/rknn_model_zoo/examples/yolov8/python/yolov8.py", line 263, in <module>
    boxes, classes, scores = post_process(outputs)
  File "/home/orangepi/rknn_model_zoo/examples/yolov8/python/yolov8.py", line 120, in post_process
    pair_per_branch = len(input_data)//defualt_branch
TypeError: object of type 'NoneType' has no len()
```

Any assistance would be appreciated. Thank you!

**Comment by youngTman** [comment]
https://github.com/airockchip/rknn_model_zoo/issues/105
