### ISSUE TITLE
转rk3588失败，显示不被支持

### ISSUE THREAD

**Issue by lzzzzz14** [airockchip/rknn_model_zoo#116]
linaro@138V001000212263:~/Desktop/rknn_model_zoo/examples/yolov8/python$ python convert.py ../yolov8n.onnx rk3588
W rknn-toolkit version: 1.7.5
--> Config model
E The target_platform contains platforms that are not currently supported.
####################
Unsupport platforms: RK3588
####################
Traceback (most recent call last):
  File "convert.py", line 46, in <module>
    [255, 255, 255]], target_platform=platform)
  File "/home/linaro/miniconda/envs/lz37/lib/python3.7/site-packages/rknn/api/rknn.py", line 753, in config
    return self.rknn_base.config(args)
  File "rknn/api/rknn_base.py", line 142, in rknn.api.rknn_base.RKNNBase.config
  File "rknn/api/npu_config/cpu_npu_mapper.py", line 89, in rknn.api.npu_config.cpu_npu_mapper.is_target_compatible
AssertionError: target_platform set as ['RK3588'] is not support

rknn-toolkit         1.7.5
在aarch64平台，debian系统

**Comment by lllittleX** [comment]
我的1.7版本也是各种不支持，我换成1.6可以用了

**Comment by VsevolodVasin** [comment]
Same error
~/rknn_model_zoo/examples/yolov8/python$ python3 convert.py ../model/yolov8n.onnx r
k3588
W rknn-toolkit version: 1.7.5
--> Config model
E The target_platform contains platforms that are not currently supported.
####################
Unsupport platforms: RK3588
####################
Traceback (most recent call last):
  File "convert.py", line 45, in <module>
    rknn.config(mean_values=[[0, 0, 0]], std_values=[
  File "/home/vsevolodvasin/anaconda3/envs/rknn/lib/python3.8/site-packages/rknn/api/rknn.py", line 753, in config
    return self.rknn_base.config(args)
  File "rknn/api/rknn_base.py", line 142, in rknn.api.rknn_base.RKNNBase.config
  File "rknn/api/npu_config/cpu_npu_mapper.py", line 89, in rknn.api.npu_config.cpu_npu_mapper.is_target_compatible
AssertionError: target_platform set as ['RK3588'] is not support
