### ISSUE TITLE
Will YOLOv10 be supported?

### ISSUE THREAD

**Issue by inmess** [airockchip/rknn_model_zoo#127]
I'm trying to deploy the latest YOLOv10 on RK3588, which is expected to be faster and more accurate than YOLOv8.
However, it seems that YOLOv10 is not yet compatible when converting with rknn-toolkit2.

```
W __init__: rknn-toolkit2 version: 1.5.2+b642f30c
--> Config model
done
--> Loading model
E load_pytorch: The following operators are not implemented: ['aten::remainder', 'aten::amax']
W load_pytorch: ===================== WARN(1) =====================
E rknn-toolkit2 version: 1.5.2+b642f30c
W load_pytorch: Catch exception when loading pytorch model: ValueError("The following operators are not implemented: ['aten::remainder', 'aten::amax']")
E load_pytorch: Traceback (most recent call last):
E load_pytorch:   File "rknn/api/rknn_base.py", line 1596, in rknn.api.rknn_base.RKNNBase.load_pytorch
E load_pytorch:   File "rknn/base/convertor/torch2onnx/pytorch.py", line 4529, in rknn.base.convertor.torch2onnx.pytorch.from_pytorch
E load_pytorch:   File "rknn/base/convertor/torch2onnx/pytorch.py", line 3624, in rknn.base.convertor.torch2onnx.pytorch.PyTorchOpConverter.report_missing_conversion
E load_pytorch:   File "rknn/api/rknn_log.py", line 112, in rknn.api.rknn_log.RKNNLog.e
E load_pytorch: ValueError: The following operators are not implemented: ['aten::remainder', 'aten::amax']
W If you can't handle this error, please try updating to the latest version of the toolkit2 and runtime from:
  https://eyun.baidu.com/s/3eTDMk6Y (Pwd: rknn)  Path: RK_NPU_SDK / RK_NPU_SDK_1.X.0 / develop /
  If the error still exists in the latest version, please collect the corresponding error logs and the model,
  convert script, and input data that can reproduce the problem, and then submit an issue on:
  https://redmine.rock-chips.com (Please consult our sales or FAE for the redmine account)
W load_pytorch: Load_pytorch exception! Try another methed!
/home/xxx/anaconda3/envs/rknn2/lib/python3.8/site-packages/torch/nn/modules/module.py:1102: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ../aten/src/ATen/native/BinaryOps.cpp:601.)
  return forward_call(*input, **kwargs)
/home/xxx/anaconda3/envs/rknn2/lib/python3.8/site-packages/torch/onnx/utils.py:100: UserWarning: `example_outputs' is deprecated and ignored. Will be removed in next PyTorch release.
  warnings.warn("`example_outputs' is deprecated and ignored. Will be removed in "
/home/xxx/anaconda3/envs/rknn2/lib/python3.8/site-packages/torch/onnx/utils.py:356: UserWarning: Model has no forward function
  warnings.warn("Model has no forward function")
W load_pytorch: Catch exception when loading pytorch model: RuntimeError('Exporting the operator amax to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.')
E load_pytorch: Traceback (most recent call last):
E load_pytorch:   File "rknn/api/rknn_base.py", line 1625, in rknn.api.rknn_base.RKNNBase.load_pytorch
E load_pytorch:   File "/home/xxx/anaconda3/envs/rknn2/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
E load_pytorch:     return utils.export(model, args, f, export_params, verbose, training,
E load_pytorch:   File "/home/xxx/anaconda3/envs/rknn2/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
E load_pytorch:     _export(model, args, f, export_params, verbose, training, input_names, output_names,
E load_pytorch:   File "/home/xxx/anaconda3/envs/rknn2/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
E load_pytorch:     _model_to_graph(model, args, verbose, input_names,
E load_pytorch:   File "/home/xxx/anaconda3/envs/rknn2/lib/python3.8/site-packages/torch/onnx/utils.py", line 497, in _model_to_graph
E load_pytorch:     graph = _optimize_graph(graph, operator_export_type,
E load_pytorch:   File "/home/xxx/anaconda3/envs/rknn2/lib/python3.8/site-packages/torch/onnx/utils.py", line 216, in _optimize_graph
E load_pytorch:     graph = torch._C._jit_pass_onnx(graph, operator_export_type)
E load_pytorch:   File "/home/xxx/anaconda3/envs/rknn2/lib/python3.8/site-packages/torch/onnx/__init__.py", line 373, in _run_symbolic_function
E load_pytorch:     return utils._run_symbolic_function(*args, **kwargs)
E load_pytorch:   File "/home/xxx/anaconda3/envs/rknn2/lib/python3.8/site-packages/torch/onnx/utils.py", line 1028, in _run_symbolic_function
E load_pytorch:     symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
E load_pytorch:   File "/home/xxx/anaconda3/envs/rknn2/lib/python3.8/site-packages/torch/onnx/utils.py", line 982, in _find_symbolic_in_registry
E load_pytorch:     return sym_registry.get_registered_op(op_name, domain, opset_version)
E load_pytorch:   File "/home/xxx/anaconda3/envs/rknn2/lib/python3.8/site-packages/torch/onnx/symbolic_registry.py", line 125, in get_registered_op
E load_pytorch:     raise RuntimeError(msg)
E load_pytorch: RuntimeError: Exporting the operator amax to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
W If you can't handle this error, please try updating to the latest version of the toolkit2 and runtime from:
  https://eyun.baidu.com/s/3eTDMk6Y (Pwd: rknn)  Path: RK_NPU_SDK / RK_NPU_SDK_1.X.0 / develop /
  If the error still exists in the latest version, please collect the corresponding error logs and the model,
  convert script, and input data that can reproduce the problem, and then submit an issue on:
  https://redmine.rock-chips.com (Please consult our sales or FAE for the redmine account)
W load_pytorch: Make sure that the torch version of './yolov10.torchscript' is consistent with the installed torch version '1.10.1+cu102'!
Load model failed!
```

**Comment by AntyRia** [comment]
me too! r u solve it?

**Comment by inmess** [comment]
> me too! r u solve it?

No, there are some ops not implemented, I was not able to convert it.

**Comment by marco0913** [comment]
is this issue solved yet?

**Comment by airockchip** [comment]
https://github.com/airockchip/rknn_model_zoo/tree/main/examples/yolov10

**Comment by marco0913** [comment]
I converted the .pt model to .onnx with the following line

!yolo export model=model format=onnx opset=13 simplify

then when I tried to convert I got this:


W __init__: rknn-toolkit2 version: 1.5.0+1fa95b5c
--> Config model
done
--> Loading model
W load_onnx: If you don't need to crop the model, don't set 'inputs'/'input_size_list'/'outputs'!
W load_onnx: Onnx opset13 is not fully supported, it may cause convert fail, it is recommended to use opset12!
Loading : 100%|█████████████████████████████████████████████████| 343/343 [00:00<00:00, 8585.19it/s]
done
--> Building model
I base_optimize ...
I base_optimize done.
I 
I fold_constant ...
E build: The input 0 of TopK('/model.23/TopK') need to be constant! It will cause the graph to be a dynamic graph!
                  Remove TopK('/model.23/TopK') manually and try again!
W build: ===================== WARN(3) =====================
E rknn-toolkit2 version: 1.5.0+1fa95b5c
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build:   File "rknn/api/rknn_base.py", line 1789, in rknn.api.rknn_base.RKNNBase.build
E build:   File "rknn/api/graph_optimizer.py", line 727, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
E build:   File "rknn/api/graph_optimizer.py", line 331, in rknn.api.graph_optimizer._dynamic_check
E build:   File "rknn/api/rknn_log.py", line 112, in rknn.api.rknn_log.RKNNLog.e
E build: ValueError: The input 0 of TopK('/model.23/TopK') need to be constant! It will cause the graph to be a dynamic graph!
E build:                   Remove TopK('/model.23/TopK') manually and try again!
W If you can't handle this error, please try updating to the latest version of the toolkit2 and runtime from:
  https://eyun.baidu.com/s/3eTDMk6Y (Pwd: rknn)  Path: RK_NPU_SDK / RK_NPU_SDK_1.X.0 / develop /
  If the error still exists in the latest version, please collect the corresponding error logs and the model,
  convert script, and input data that can reproduce the problem, and then submit an issue on:
  https://redmine.rock-chips.com (Please consult our sales or FAE for the redmine account)
Build model failed!
