### ISSUE TITLE
导出.torchscript成功，转换rknn失败

### ISSUE THREAD

**Issue by zhaotun** [airockchip/rknn_model_zoo#15]
根据 [airockchip](https://github.com/airockchip)/[yolov5](https://github.com/airockchip/yolov5) 使用
```python  
python export.py --rknpu rk3399pro
```
命令成功导出了 yolov5s.torchscript ， 然后在rknn-toolkit-1.7.0 的docker里，进入
 ```shell
rknn_model_zoo/models/CV/object_detection/yolo/RKNN_model_convert
```
yolov5_yolov7.yml内容为：
```shell
model_name: yolov5_yolov7
model_framework: pytorch
model_file_path: yolov5s.torchscript
RK_device_platform: RK3399PRO
RK_device_id: simulator
dataset: ../../../../../datasets/COCO/coco_dataset_20.txt
quantize: False
pre_compile: online

graph:
  in_0:
    shape: 3,640,640
    mean_values: 0
    std_values: 255
    img_type: RGB

configs:
  quantized_dtype: asymmetric_quantized-8
  quantized_algorithm: normal
  optimization_level: 3
```
执行
```shell
./convert_yolov5_yolov7.sh 
```
报以下错误
```shell
|| ./../../../../../datasets/COCO/val2017/000000468505.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000570664.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000359781.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000521819.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000001818.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000369675.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000017627.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000039956.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000430875.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000057672.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000157213.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000481480.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000577539.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000406570.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000300659.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000078032.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000471756.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000270402.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000174482.jpg || input path in dataset.txt not exist, compute convert loss will be failed
|| ./../../../../../datasets/COCO/val2017/000000193884.jpg || input path in dataset.txt not exist, compute convert loss will be failed
========== parser_config ==========
NPU_VERSION: 1
RK_device_platform: RK3399PRO
input_example: [{'in_0': './../../../../../datasets/COCO/val2017/000000468505.jpg'}, {'in_0': './../  ...
pre_compile: online
core_mask: 1
config:
  target_platform: RK3399PRO
  quantized_dtype: asymmetric_affine-u8
  quantized_algorithm: normal
  optimization_level: 3
  mean_values: [[0, 0, 0]]
  std_values: [[255, 255, 255]]
  mmse_epoch: 3
  do_sparse_network: True
  output_optimize: 0
  batch_size: 100
  quantize_input_node: False
  merge_dequant_layer_and_output_node: False
  force_builtin_perm: False
  reorder_channel: 0 1 2
export_rknn:
  export_path: ./model_cvt/RK1808_3399pro/yolov5_yolov7_RK1808_3399pro_fp.rknn
verbose: False
dataset: ./../../../../../datasets/COCO/coco_dataset_20.txt
quantize: False
build:
  do_quantization: False
  dataset: ./../../../../../datasets/COCO/coco_dataset_20.txt
model_framework: pytorch
qnnpack: False
load:
  model: ./yolov5s.torchscript
  input_size_list: [[3, 640, 640]]
inputs:
  in_0:
    shape: [3, 640, 640]
    mean_values: [0, 0, 0]
    std_values: [255, 255, 255]
    img_type: RGB
outputs:
RK_device_id: simulator
export_pre_compile_path: ./model_cvt/RK1808_3399pro/yolov5_yolov7_RK1808_3399pro_fp_precompile.rknn
===================================
---> Create RKNN object
---> Seting RKNN config
Traceback (most recent call last):
  File "../../../../../common/rknn_converter/rknn_convert.py", line 79, in <module>
    convert(config_dict, args)
  File "../../../../../common/rknn_converter/rknn_convert.py", line 19, in convert
    rknn = cp.convert()
  File "/test/rknn_model_zoo/common/rknn_converter/phase.py", line 96, in convert
    rknn.config(**model_config_dict['config'])
TypeError: config() got an unexpected keyword argument 'quantize_input_node'

```

**Comment by GuardSkill** [comment]
我用1.7.3做rknn3399Pro的转换也报同样的错误
