### ISSUE TITLE
PPOCR-System 有些字体无法识别到，比如大写的“J”就没办法识别出来

### ISSUE THREAD

**Issue by EricsZhou** [airockchip/rknn_model_zoo#171]
PPOCR-System 有些字体无法识别到，比如大写的“J”就没办法识别出来，我尝试在dict.h文件的std::string ocr_dict[6625]字符串里面添加大写的“J”，因为这个ocr_dict没有我以为和这个有关但是发现还是不行，请问要怎么做才能识别出大写的“J”？

**Comment by clsyc** [comment]
你好，我也使用的PPOCR-Syetem但是在Det分区域的时候出现了输入图像尺寸的问题（官方示例代码），请问您遇到过么？如何解决的？
Traceback (most recent call last):
  File "/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_system.py", line 143, in <module>
    filter_boxes, filter_rec_res = system_model.run(img)
  File "/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_system.py", line 36, in run
    dt_boxes = self.text_detector.run(img)
  File "/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_det.py", line 104, in run
    output = self.model.run([model_input['image']])
  File "/home/orangepi/rknn_model_zoo/py_utils/onnx_executor.py", line 66, in run
    assert False, 'input shape{} not match real data shape{}'.format(_input.shape, input_datas[i].shape)
AssertionError: input shape[1, 3, 48, 320] not match real data shape(1, 3, 480, 480)

**Comment by EricsZhou** [comment]
看意思是你的图片输入不对，你得把你的图片缩放rsize一下成48*320的图片大小，你现在输入的图片大小是480*480所以会报错&nbsp;


朝颜丶陪你到世界终结
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月22日(星期天) 晚上11:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [airockchip/rknn_model_zoo] PPOCR-System 有些字体无法识别到，比如大写的“J”就没办法识别出来 (Issue #171)















你好，我也使用的PPOCR-Syetem但是在Det分区域的时候出现了输入图像尺寸的问题（官方示例代码），请问您遇到过么？如何解决的？
追溯（最近一次通话时间）：
文件"/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_system.py",第143行，在
过滤框，过滤结果 = system_model.run（img）
文件"/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_system.py",第36行，在运行中
dt_boxes = self.text_detector.run(img)
文件"/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_det.py",第104行，在运行中
输出 = self.model.run（[model_input['image']]）
文件"/home/orangepi/rknn_model_zoo/py_utils/onnx_executor.py",第65行，运行中
断言 False，'输入形状{}不匹配真实数据形状{}'.format（_input.shape， input_datas[i].shape）
断言错误:输入形状[1， 3， 48， 320]不匹配实际数据形状（1， 3， 480， 480）

-
直接回复此邮件，在GitHub上查看它，或取消订阅.
***@***.*** &gt;

**Comment by clsyc** [comment]
> 看意思是你的图片输入不对，你得把你的图片缩放rsize一下成48*320的图片大小，你现在输入的图片大小是480*480所以会报错&nbsp; 朝颜丶陪你到世界终结 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年12月22日(星期天) 晚上11:20 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [airockchip/rknn_model_zoo] PPOCR-System 有些字体无法识别到，比如大写的“J”就没办法识别出来 (Issue #171) 你好，我也使用的PPOCR-Syetem但是在Det分区域的时候出现了输入图像尺寸的问题（官方示例代码），请问您遇到过么？如何解决的？ 追溯（最近一次通话时间）： 文件"/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_system.py",第143行，在 过滤框，过滤结果 = system_model.run（img） 文件"/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_system.py",第36行，在运行中 dt_boxes = self.text_detector.run(img) 文件"/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_det.py",第104行，在运行中 输出 = self.model.run（[model_input['image']]） 文件"/home/orangepi/rknn_model_zoo/py_utils/onnx_executor.py",第65行，运行中 断言 False，'输入形状{}不匹配真实数据形状{}'.format（_input.shape， input_datas[i].shape） 断言错误:输入形状[1， 3， 48， 320]不匹配实际数据形状（1， 3， 480， 480） - 直接回复此邮件，在GitHub上查看它，或取消订阅. ***@***.*** &gt;

我试过resize成48*320大小，但是还是报错，你运行官方python代码没有遇到过该问题么？

**Comment by EricsZhou** [comment]
我是跑的c++版本，他的工作流程我大致看过他有二个模型一个是480*480的模型，48*320的模型，他这用二个模型是因为他会先用480*480的模型定位文字大致的位置，然后通过48*320具体识别出文字的具体内容，你可以看一下你python代码的处理逻辑看是哪一步模型处理出错了，然后按照对应的进行修改就行

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: clsyc ***@***.***&gt;
发送时间: 2024年12月24日 21:55
收件人: airockchip/rknn_model_zoo ***@***.***&gt;
抄送: EricsZhou ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [airockchip/rknn_model_zoo] PPOCR-System 有些字体无法识别到，比如大写的“J”就没办法识别出来 (Issue #171)





  
看意思是你的图片输入不对，你得把你的图片缩放rsize一下成48320的图片大小，你现在输入的图片大小是480480所以会报错&nbsp; 朝颜丶陪你到世界终结 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年12月22日(星期天) 晚上11:20 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [airockchip/rknn_model_zoo] PPOCR-System 有些字体无法识别到，比如大写的“J”就没办法识别出来 (Issue #171) 你好，我也使用的PPOCR-Syetem但是在Det分区域的时候出现了输入图像尺寸的问题（官方示例代码），请问您遇到过么？如何解决的？ 追溯（最近一次通话时间）： 文件"/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_system.py",第143行，在 过滤框，过滤结果 = system_model.run（img） 文件"/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_system.py",第36行，在运行中 dt_boxes = self.text_detector.run(img) 文件"/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_det.py",第104行，在运行中 输出 = self.model.run（[model_input['image']]） 文件"/home/orangepi/rknn_model_zoo/py_utils/onnx_executor.py",第65行，运行中 断言 False，'输入形状{}不匹配真实数据形状{}'.format（_input.shape， input_datas[i].shape） 断言错误:输入形状[1， 3， 48， 320]不匹配实际数据形状（1， 3， 480， 480） - 直接回复此邮件，在GitHub上查看它，或取消订阅. @.*** &gt;
  
我试过resize成48*320大小，但是还是报错，你运行官方python代码没有遇到过该问题么？

**Comment by clsyc** [comment]
> 我是跑的c++版本，他的工作流程我大致看过他有二个模型一个是480*480的模型，48*320的模型，他这用二个模型是因为他会先用480*480的模型定位文字大致的位置，然后通过48*320具体识别出文字的具体内容，你可以看一下你python代码的处理逻辑看是哪一步模型处理出错了，然后按照对应的进行修改就行 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: clsyc ***@***.***&gt; 发送时间: 2024年12月24日 21:55 收件人: airockchip/rknn_model_zoo ***@***.***&gt; 抄送: EricsZhou ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [airockchip/rknn_model_zoo] PPOCR-System 有些字体无法识别到，比如大写的“J”就没办法识别出来 (Issue #171) 看意思是你的图片输入不对，你得把你的图片缩放rsize一下成48320的图片大小，你现在输入的图片大小是480480所以会报错&nbsp; 朝颜丶陪你到世界终结 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年12月22日(星期天) 晚上11:20 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [airockchip/rknn_model_zoo] PPOCR-System 有些字体无法识别到，比如大写的“J”就没办法识别出来 (Issue #171) 你好，我也使用的PPOCR-Syetem但是在Det分区域的时候出现了输入图像尺寸的问题（官方示例代码），请问您遇到过么？如何解决的？ 追溯（最近一次通话时间）： 文件"/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_system.py",第143行，在 过滤框，过滤结果 = system_model.run（img） 文件"/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_system.py",第36行，在运行中 dt_boxes = self.text_detector.run(img) 文件"/home/orangepi/rknn_model_zoo/examples/PPOCR/PPOCR-System/python/ppocr_det.py",第104行，在运行中 输出 = self.model.run（[model_input['image']]） 文件"/home/orangepi/rknn_model_zoo/py_utils/onnx_executor.py",第65行，运行中 断言 False，'输入形状{}不匹配真实数据形状{}'.format（_input.shape， input_datas[i].shape） 断言错误:输入形状[1， 3， 48， 320]不匹配实际数据形状（1， 3， 480， 480） - 直接回复此邮件，在GitHub上查看它，或取消订阅. @.*** &gt; 我试过resize成48*320大小，但是还是报错，你运行官方python代码没有遇到过该问题么？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

好的好的，非常感谢！

**Comment by zzh805780186** [comment]
请问有遇到过c++版本 ocr检测的框不对，但是python版本 ocr检测框对的情况吗？
