### ISSUE TITLE
yolov5 rk3588

### ISSUE THREAD

**Issue by CactysFedya** [airockchip/rknn_model_zoo#173]
Hello! please tell me how to convert yolov5's own detection model to rknn format?

**Comment by CactysFedya** [comment]
[W830 12:57:49.304176644 NNPACK.cpp:61] Could not initialize NNPACK! Reason: Unsupported hardware.
YOLOv5s summary (fused): 193 layers, 9115406 parameters, 0 gradients, 23.8 GFLOPs
export detect model for RKNPU
Traceback (most recent call last):
  File "/home/energia/rknn/yolov5/export.py", line 723, in <module>
    main(opt)
  File "/home/energia/rknn/yolov5/export.py", line 717, in main
    run(**vars(opt))
  File "/home/energia/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/energia/rknn/yolov5/export.py", line 616, in run
    model.model[-1]._register_detect_seperate(True)
  File "/home/energia/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Detect' object has no attribute '_register_detect_seperate'
