### ISSUE TITLE
rknn_model_zoo转换rv1126失败

### ISSUE THREAD

**Issue by guo010699** [airockchip/rknn_model_zoo#191]
I rknn-toolkit2 version: 2.0.0b0+9bab5682
--> Config model
E config: Invalid target_platform 'rv1126'!
I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.0.0b0+9bab5682
Traceback (most recent call last):
  File "convert.py", line 49, in <module>
    rknn.config(mean_values=[[0, 0, 0]], std_values=[
  File "/home/gcl/miniconda3/envs/rknn/lib/python3.8/site-packages/rknn/api/rknn.py", line 128, in config
    return self.rknn_base.config(args)
  File "rknn/api/rknn_base.py", line 952, in rknn.api.rknn_base.RKNNBase.config
  File "rknn/api/rknn_log.py", line 92, in rknn.api.rknn_log.RKNNLog.e
ValueError: Invalid target_platform 'rv1126'!
有一个这个报错，我使用的版本是rknn-toolkit2 version: 2.0.0b0+9bab5682，然后在PC端进行的转换，说不支持？

**Comment by zen-xingle** [comment]
RV1126使用下面这个版本的 toolkit，两者不兼容
RKNN-Toolkit1 v1.7.3 (for RK3399pro/RK1808/RV1126/RV1109)
https://github.com/rockchip-linux/rknn-toolkit
