### ISSUE TITLE
error about yolov8 pt model

### ISSUE THREAD

**Issue by lxy1015** [airockchip/rknn_model_zoo#202]
The python demo in the yolov8 folder cannot use the pt file

Traceback (most recent call last):
  File "yolov8.py", line 221, in <module>
    model, platform = setup_model(args)
  File "yolov8.py", line 180, in setup_model
    model = Torch_model_container(args.model_path)
  File "/home/cas/Desktop/rknn_model_zoo/py_utils/pytorch_executor.py", line 21, in __init__
    self.pt_model = torch.jit.load(model_path)
  File "/home/cas/miniconda3/lib/python3.8/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found
Exception ignored in: <function Torch_model_container.__del__ at 0x75ffacacf4c0>
Traceback (most recent call last):
  File "/home/cas/Desktop/rknn_model_zoo/py_utils/pytorch_executor.py", line 25, in __del__
    self.release()
  File "/home/cas/Desktop/rknn_model_zoo/py_utils/pytorch_executor.py", line 61, in release
    del self.pt_model

**Comment by zen-xingle** [comment]
The .pt model should be saved via 'torch.jit.trace & torch.jit.save' API. NOT 'torch.save'.

**Comment by zoldaten** [comment]
try .onnx variant should work
