### ISSUE TITLE
2.3版本yolov8_seg在rk3588推理报错

### ISSUE THREAD

**Issue by zhangJoel** [airockchip/rknn_model_zoo#214]
x86打包，toolkit2版本为2.3，model_zoo也更新到了2.3，rk3588板环境为2.3。

打包cpp成可执行程序，拷贝到rk3588推理的时候报错。错误如下，lib库也是2.3版本里的最新版本
```

sudo ./rknn_yolov8_seg_demo model/yolov8_seg.rknn model/bus.jpg
load lable ./model/coco_80_labels_list.txt
E RKNN: [15:17:18.225] 6, 1
E RKNN: [15:17:18.225] Invalid RKNN model version 6
E RKNN: [15:17:18.226] rknn_init, load model failed!
rknn_init fail! ret=-1
init_yolov8_seg_model fail! ret=-1 model_path=model/yolov8_seg.rknn

```

x86打包编译环境 tk版本 2.3：
```
Python 3.8.20 (default, Oct  3 2024, 15:24:27)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rknn.api import RKNN
>>> rknn = RKNN()
I rknn-toolkit2 version: 2.3.0

```

rk3588板端rkpu版本：
```
zysj-sz@linux:~/Downloads/rknn_yolov8_seg_demo$ strings /usr/bin/rknn_server | grep -i "rknn_server version"
rknn_server version: 2.3.0 (e80ac5c build@2024-11-07T12:52:53)
zysj-sz@linux:~/Downloads/rknn_yolov8_seg_demo$ strings /usr/lib/librknnrt.so | grep -i "librknnrt version"
librknnrt version: 2.3.0 (c949ad889d@2024-11-07T11:35:33)
```

**Comment by jxx-xi** [comment]
> x86打包，toolkit2版本为2.3，model_zoo也更新到了2.3，rk3588板环境为2.3。
> 
> 打包cpp成可执行程序，拷贝到rk3588推理的时候报错。错误如下，lib库也是2.3版本里的最新版本
> 
> ```
> 
> sudo ./rknn_yolov8_seg_demo model/yolov8_seg.rknn model/bus.jpg
> load lable ./model/coco_80_labels_list.txt
> E RKNN: [15:17:18.225] 6, 1
> E RKNN: [15:17:18.225] Invalid RKNN model version 6
> E RKNN: [15:17:18.226] rknn_init, load model failed!
> rknn_init fail! ret=-1
> init_yolov8_seg_model fail! ret=-1 model_path=model/yolov8_seg.rknn
> ```
> 
> x86打包编译环境 tk版本 2.3：
> 
> ```
> Python 3.8.20 (default, Oct  3 2024, 15:24:27)
> [GCC 11.2.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from rknn.api import RKNN
> >>> rknn = RKNN()
> I rknn-toolkit2 version: 2.3.0
> ```
> 
> rk3588板端rkpu版本：
> 
> ```
> zysj-sz@linux:~/Downloads/rknn_yolov8_seg_demo$ strings /usr/bin/rknn_server | grep -i "rknn_server version"
> rknn_server version: 2.3.0 (e80ac5c build@2024-11-07T12:52:53)
> zysj-sz@linux:~/Downloads/rknn_yolov8_seg_demo$ strings /usr/lib/librknnrt.so | grep -i "librknnrt version"
> librknnrt version: 2.3.0 (c949ad889d@2024-11-07T11:35:33)
> ```

看报错信息，应该是模型版本不对，或者是其他平台的模型，请重新转一下模型试试

**Comment by zoldaten** [comment]
i have the same issue with yolo11.rknn detection on rk3566:
```
python3 yolo11.py --model_path yolo11.rknn --target rk3566
I rknn-toolkit2 version: 2.3.0
--> Init runtime environment
I target set by user is: rk3566
E RKNN: [02:59:59.948] 6, 1
E RKNN: [02:59:59.949] Invalid RKNN model version 6
E RKNN: [02:59:59.949] rknn_init, load model failed!
E init_runtime: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2483, in rknn.api.rknn_base.RKNNBase.init_runtime
  File "rknn/api/rknn_runtime.py", line 427, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.3.0
Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2483, in rknn.api.rknn_base.RKNNBase.init_runtime
  File "rknn/api/rknn_runtime.py", line 427, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yolo11.py", line 221, in <module>
    model, platform = setup_model(args)
  File "yolo11.py", line 184, in setup_model
    model = RKNN_model_container(args.model_path, args.target, args.device_id)
  File "/home/luckfox/rknn_model_zoo/py_utils/rknn_executor.py", line 15, in __init__
    ret = rknn.init_runtime(target=target, device_id=device_id)
  File "/home/luckfox/.local/lib/python3.8/site-packages/rknn/api/rknn.py", line 295, in init_runtime
    return self.rknn_base.init_runtime(target=target, device_id=device_id,
  File "rknn/api/rknn_log.py", line 349, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 2483, in rknn.api.rknn_base.RKNNBase.init_runtime
  File "rknn/api/rknn_runtime.py", line 427, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL
```

**since i have copy-paste librknnrt.so
from here:
https://github.com/rockchip-linux/rknpu2/blob/master/runtime/RK356X/Linux/librknn_api/aarch64/librknnrt.so
and put it to /usr/lib i see this error now:**

```
python3 yolo11.py --model_path yolo11.rknn --target rk3566                          I rknn-toolkit2 version: 2.3.0
--> Init runtime environment
I target set by user is: rk3566
done
Model-yolo11.rknn is rknn model, starting val
W inference: The 'data_format' is not set, and its default value is 'nhwc'!
Traceback (most recent call last):
  File "yolo11.py", line 265, in <module>
    boxes, classes, scores = post_process(outputs)
  File "yolo11.py", line 123, in post_process
    boxes.append(box_process(input_data[pair_per_branch*i]))
  File "yolo11.py", line 103, in box_process
    grid_h, grid_w = position.shape[2:4]
ValueError: not enough values to unpack (expected 2, got 1)
```

postprocess should be fix, i think.
and there is something with model convertion itself:
```
python3 convert.py yolo11n.onnx rk3566
I rknn-toolkit2 version: 2.3.0
--> Config model
done
--> Loading model
I Loading : 100%|███████████████████████████████████████████████| 196/196 [00:00<00:00, 6059.03it/s]
done
--> Building model
I OpFusing 0: 100%|███████████████████████████████████████████████| 100/100 [00:02<00:00, 39.52it/s]
I OpFusing 1 : 100%|██████████████████████████████████████████████| 100/100 [00:06<00:00, 15.84it/s]
I OpFusing 0 : 100%|██████████████████████████████████████████████| 100/100 [00:10<00:00,  9.14it/s]
I OpFusing 1 : 100%|██████████████████████████████████████████████| 100/100 [00:12<00:00,  8.07it/s]
I OpFusing 0 : 100%|██████████████████████████████████████████████| 100/100 [00:13<00:00,  7.52it/s]
I OpFusing 1 : 100%|██████████████████████████████████████████████| 100/100 [00:13<00:00,  7.21it/s]
I OpFusing 2 : 100%|██████████████████████████████████████████████| 100/100 [00:18<00:00,  5.31it/s]
W build: found outlier value, this may affect quantization accuracy
                        const name                          abs_mean    abs_std     outlier value
                        model.23.cv3.1.1.1.conv.weight      0.55        0.60        -12.173
                        model.23.cv3.0.0.0.conv.weight      0.25        0.35        -15.593
I GraphPreparing : 100%|█████████████████████████████████████████| 243/243 [00:01<00:00, 149.93it/s]
I Quantizating : 100%|████████████████████████████████████████████| 243/243 [01:06<00:00,  3.64it/s]
W build: The default input dtype of 'images' is changed from 'float32' to 'int8' in rknn model for performance!
                       Please take care of this change when deploy rknn model with Runtime API!
W build: The default output dtype of 'output0' is changed from 'float32' to 'int8' in rknn model for performance!
                      Please take care of this change when deploy rknn model with Runtime API!
I rknn building ...
I rknn building done.
done
--> Export rknn model
done
```

**Comment by zhangJoel** [comment]
@zoldaten Thanks for sharing your solution very much!

**Comment by diamondt5353** [comment]
@zhangJoel 佬，有众云世纪的固件吗？rk3588 ,zysj-2288a

**Comment by jxhexi** [comment]
同求，zysj-2288a， rk3588固件
