### ISSUE TITLE
RV1126 missing in latest as well as v2.0.0

### ISSUE THREAD

**Issue by openedev** [airockchip/rknn_model_zoo#219]
In 2.3.0
```
$ python convert.py yolov8n.onnx rv1126
I rknn-toolkit2 version: 2.2.0
--> Config model
E config: Invalid target_platform 'rv1126'!
I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.2.0
E config: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 881, in rknn.api.rknn_base.RKNNBase.config
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Invalid target_platform 'rv1126'!

I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.2.0
Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 881, in rknn.api.rknn_base.RKNNBase.config
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Invalid target_platform 'rv1126'!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/build/shared/rknn_model_zoo/examples/yolov8/python/convert.py", line 45, in <module>
    rknn.config(mean_values=[[0, 0, 0]], std_values=[
  File "/home/build/conda/lib/python3.12/site-packages/rknn/api/rknn.py", line 119, in config
    return self.rknn_base.config(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "rknn/api/rknn_log.py", line 314, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 881, in rknn.api.rknn_base.RKNNBase.config
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Invalid target_platform 'rv1126'!
```

In v2.0.0
```
$ python convert.py yolov8n.onnx rv1126
I rknn-toolkit2 version: 2.2.0
--> Config model
E config: Invalid target_platform 'rv1126'!
I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.2.0
E config: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 881, in rknn.api.rknn_base.RKNNBase.config
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Invalid target_platform 'rv1126'!

I ===================== WARN(0) =====================
E rknn-toolkit2 version: 2.2.0
Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 881, in rknn.api.rknn_base.RKNNBase.config
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Invalid target_platform 'rv1126'!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/build/shared/rknn_model_zoo/examples/yolov8/python/convert.py", line 45, in <module>
    rknn.config(mean_values=[[0, 0, 0]], std_values=[
  File "/home/build/conda/lib/python3.12/site-packages/rknn/api/rknn.py", line 119, in config
    return self.rknn_base.config(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "rknn/api/rknn_log.py", line 314, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 881, in rknn.api.rknn_base.RKNNBase.config
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Invalid target_platform 'rv1126'!
```

**Comment by jxx-xi** [comment]
> In 2.3.0
> 
> ```
> $ python convert.py yolov8n.onnx rv1126
> I rknn-toolkit2 version: 2.2.0
> --> Config model
> E config: Invalid target_platform 'rv1126'!
> I ===================== WARN(0) =====================
> E rknn-toolkit2 version: 2.2.0
> E config: Traceback (most recent call last):
>   File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
>   File "rknn/api/rknn_base.py", line 881, in rknn.api.rknn_base.RKNNBase.config
>   File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
> ValueError: Invalid target_platform 'rv1126'!
> 
> I ===================== WARN(0) =====================
> E rknn-toolkit2 version: 2.2.0
> Traceback (most recent call last):
>   File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
>   File "rknn/api/rknn_base.py", line 881, in rknn.api.rknn_base.RKNNBase.config
>   File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
> ValueError: Invalid target_platform 'rv1126'!
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/build/shared/rknn_model_zoo/examples/yolov8/python/convert.py", line 45, in <module>
>     rknn.config(mean_values=[[0, 0, 0]], std_values=[
>   File "/home/build/conda/lib/python3.12/site-packages/rknn/api/rknn.py", line 119, in config
>     return self.rknn_base.config(args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "rknn/api/rknn_log.py", line 314, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
>   File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
> ValueError: Traceback (most recent call last):
>   File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
>   File "rknn/api/rknn_base.py", line 881, in rknn.api.rknn_base.RKNNBase.config
>   File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
> ValueError: Invalid target_platform 'rv1126'!
> ```
> 
> In v2.0.0
> 
> ```
> $ python convert.py yolov8n.onnx rv1126
> I rknn-toolkit2 version: 2.2.0
> --> Config model
> E config: Invalid target_platform 'rv1126'!
> I ===================== WARN(0) =====================
> E rknn-toolkit2 version: 2.2.0
> E config: Traceback (most recent call last):
>   File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
>   File "rknn/api/rknn_base.py", line 881, in rknn.api.rknn_base.RKNNBase.config
>   File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
> ValueError: Invalid target_platform 'rv1126'!
> 
> I ===================== WARN(0) =====================
> E rknn-toolkit2 version: 2.2.0
> Traceback (most recent call last):
>   File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
>   File "rknn/api/rknn_base.py", line 881, in rknn.api.rknn_base.RKNNBase.config
>   File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
> ValueError: Invalid target_platform 'rv1126'!
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/build/shared/rknn_model_zoo/examples/yolov8/python/convert.py", line 45, in <module>
>     rknn.config(mean_values=[[0, 0, 0]], std_values=[
>   File "/home/build/conda/lib/python3.12/site-packages/rknn/api/rknn.py", line 119, in config
>     return self.rknn_base.config(args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "rknn/api/rknn_log.py", line 314, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
>   File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
> ValueError: Traceback (most recent call last):
>   File "rknn/api/rknn_log.py", line 309, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
>   File "rknn/api/rknn_base.py", line 881, in rknn.api.rknn_base.RKNNBase.config
>   File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
> ValueError: Invalid target_platform 'rv1126'!
> ```
rv1126/rv1109/rk1808 belongs to rknpu1, please use rknn-toolkit1, reference link:
https://github.com/rockchip-linux/rknn-toolkit
