### ISSUE TITLE
I want to convert the yolov8-obb model which trained myself to RKNN,But it donesn't works?

### ISSUE THREAD

**Issue by Mcaft** [airockchip/rknn_model_zoo#221]
When I convert it,It warn me this :
W build: Show op fuse match nodes:
Rule: reduce_reshape_op_around_concat
Subgraph:
Op type: Concat
Op name: /model.22/Cos_output_0_concat
  Input:
    /model.22/Cos_output_0_rs : [1, 1, 1, 8400]
    /model.22/Sin_output_0_rs : [1, 1, 1, 8400]
    /model.22/Cos_output_0_rs : [1, 1, 1, 8400]
  Output:
    /model.22/Cos_output_0_concat-rs : [1, 3, 1, 8400]
  Attribute:
    axis : 1
 

W You can add disable_rules=['reduce_reshape_op_around_concat'] in rknn.config() to temporarily disable the error rule!

E build: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1962, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 2108, in rknn.api.graph_optimizer.GraphOptimizer.fuse_ops
  File "rknn/api/ir_graph.py", line 1772, in rknn.api.ir_graph.IRGraph.remove_nodes
  File "rknn/api/ir_graph.py", line 1730, in rknn.api.ir_graph.IRGraph.remove_node
KeyError: '/model.22/Cos_output_0_rs'

**Comment by Spidrre** [comment]
Hey, I'm having the same kind of issue here, have you been able to solve this task?

**Comment by Mcaft** [comment]
yes,I have found that there is a model in python named ultralystics,which must be installed locally in rockchip 's yolov8obb so that you can train the right nn model on your PC,then convert it into rknn.The right model output have four output head,you can have a gui view of model on Netron

**Comment by Mcaft** [comment]
yes,I have found that there is a model in python named ultralystics,which must be installed locally in rockchip 's yolov8obb so that you can train the right nn model on your PC,then convert it into rknn.The right model output have four output head,you can have a gui view of model on Netron



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 18, 2025 13:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [airockchip/rknn_model_zoo] I want to convert the yolov8-obbmodel which trained myself to RKNN,But it donesn't works? (Issue #221)


   
Hey, I'm having the same kind of issue here, have you been able to solve this task?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  Spidrre left a comment (airockchip/rknn_model_zoo#221)
 
Hey, I'm having the same kind of issue here, have you been able to solve this task?

**Comment by Spidrre** [comment]
Huh, that's weird, because I have trained ultralytic's YOLOv8 OBB on my PC, then tried converting it to the ONNX, but couldn't unless I have set disable_rules=['reduce_reshape_op_around_concat'] in rknn.config()
