### ISSUE TITLE
使用官方ppocrv4 rec转rknn报错   det没有问题

### ISSUE THREAD

**Issue by Zomcxj** [airockchip/rknn_model_zoo#226]
按照Paddle_2_ONNX.md将模型转至onnx

python convert.py ../model/ppocrv4_rec.onnx rk3588 fp
W __init__: rknn-toolkit2 version: 1.5.0+1fa95b5c
--> Config model
done
--> Loading model
E load_onnx: Catch exception when loading onnx model: /home/cxj/cxj/CPP/rknn_model_zoo-2.3.0/examples/PPOCR/PPOCR-Rec/model/ppocrv4_rec.onnx!
E load_onnx: Traceback (most recent call last):
E load_onnx:   File "rknn/api/rknn_base.py", line 1382, in rknn.api.rknn_base.RKNNBase.load_onnx
E load_onnx:   File "rknn/api/rknn_base.py", line 658, in rknn.api.rknn_base.RKNNBase._create_ir_and_inputs_meta
E load_onnx:   File "rknn/api/ir_graph.py", line 58, in rknn.api.ir_graph.IRGraph.__init__
E load_onnx:   File "rknn/api/ir_graph.py", line 503, in rknn.api.ir_graph.IRGraph.rebuild
E load_onnx:   File "/home/cxj/anaconda3/envs/rknn/lib/python3.6/site-packages/onnx/checker.py", line 106, in check_model
E load_onnx:     C.check_model(protobuf_string)
E load_onnx: onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of type is required but missing.
W If you can't handle this error, please try updating to the latest version of the toolkit2 and runtime from:
  https://eyun.baidu.com/s/3eTDMk6Y (Pwd: rknn)  Path: RK_NPU_SDK / RK_NPU_SDK_1.X.0 / develop /
  If the error still exists in the latest version, please collect the corresponding error logs and the model,
  convert script, and input data that can reproduce the problem, and then submit an issue on:
  https://redmine.rock-chips.com (Please consult our sales or FAE for the redmine account)
Load model failed!

**Comment by Zomcxj** [comment]
v4 det 和v3 det rec可以转换  cls和v4rec有问题

**Comment by ZH-1225** [comment]
> 使用Paddle2ONNX\tools\onnx\onnx_infer_shape.py即可解决报错

麻烦问一下这个文件在哪里
