### ISSUE TITLE
关于语音zipformer模型的支持

### ISSUE THREAD

**Issue by chris1992212** [airockchip/rknn_model_zoo#230]
你好，请问后续有计划支持其他的zipformer模型，我这边尝试了kws-zipformer-wenetspeech-3.3M-2024-01-01这个模型，无法转rknn。
log如下：

E build: Can not find tensor value info for 'embed_states'!
W build: ===================== WARN(3) =====================
E rknn-toolkit2 version: 2.3.0
E build: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1945, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 886, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: Can not find tensor value info for 'embed_states'!

**Comment by csukuangfj** [comment]
> 我这边尝试了kws-zipformer-wenetspeech-3.3M-2024-01-01这个模型

需要用 rknntoolkit 2.2， 才能转 @chris1992212

**Comment by ErwinCheung** [comment]
> > 我这边尝试了kws-zipformer-wenetspeech-3.3M-2024-01-01这个模型
> 
> 需要用 rknntoolkit 2.2， 才能转 [@chris1992212](https://github.com/chris1992212)

Kuang哥，请问你们开源的kws-zipformer轻量级模型有支持日语的吗？我找了一些，全是英文+汉语的。

**Comment by csukuangfj** [comment]
目前没有
