### ISSUE TITLE
RK3588 Exception: Unsupported run platform: Linux aarch64

### ISSUE THREAD

**Issue by yongju-Shin** [airockchip/rknn_model_zoo#231]
I am using an RK3588 platform and Python 3.8.10, with rknn_toolkit_lite2-2.3.0-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl installed.

I also downloaded the librknnrt.so file from the following link:
https://github.com/rockchip-linux/rknpu2/raw/master/runtime/RK3588/Linux/librknn_api/aarch64/librknnrt.so

Then, I placed it in /usr/lib/ using the following command:
```
sudo mv librknnrt.so /usr/lib/librknnrt.so
```
However, when I try to run the YOLO example, I encounter the following error. 

```
/rknn_model_zoo/examples/yolov8/python$ python3 yolov8.py --model_path /home/linaro/yolov8.rknn --target rk3588 --img_show
W rknn-toolkit-lite2 version: 2.3.0
--> Init runtime environment
E Catch exception when init runtime!
E Traceback (most recent call last):
  File "/home/linaro/.local/lib/python3.11/site-packages/rknnlite/api/rknn_lite.py", line 148, in init_runtime
    self.rknn_runtime = RKNNRuntime(root_dir=self.root_dir, target=target, device_id=device_id,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "rknnlite/api/rknn_runtime.py", line 363, in rknnlite.api.rknn_runtime.RKNNRuntime.__init__
  File "rknnlite/api/rknn_runtime.py", line 607, in rknnlite.api.rknn_runtime.RKNNRuntime._load_library
  File "rknnlite/api/rknn_runtime.py", line 602, in rknnlite.api.rknn_runtime.RKNNRuntime._get_rknn_api_lib_path
Exception: Unsupported run platform: Linux aarch64

Init runtime environment failed
```

Is there any solution for this issue?

**Comment by Keele520** [comment]
Please try use with this librknnrt.so
https://github.com/airockchip/rknn-toolkit2/blob/master/rknpu2/runtime/Linux/librknn_api/aarch64/librknnrt.so

**Comment by yongju-Shin** [comment]
<img width="1194" alt="스크린샷 2024-12-06 오후 5 09 42" src="https://github.com/user-attachments/assets/dd8d6443-7714-4036-88e0-1744d40d2c38">


Thank you for your response.
However, I am still encountering the same issue.
Are there any other solutions?

**Comment by Keele520** [comment]
open this filer "rknn_model_zoo/py_utils/rknn_executor.py"

edit from :

print('--> Init runtime environment')
        if target==None:
            ret = rknn.init_runtime()
        else:
            ret = rknn.init_runtime(target=target, device_id=device_id)

to : 

print('--> Init runtime environment')
        #if target==None:
        #    ret = rknn.init_runtime()
        #else:
        #    ret = rknn.init_runtime(target=target, device_id=device_id)
        ret = rknn.init_runtime()

then try run again your code.

**Comment by yongju-Shin** [comment]
Thank you for your help in resolving the issue.

**Comment by KZI-22** [comment]
解决了吗，我也遇到了这个问题

**Comment by KZI-22** [comment]
Did you solve this issue? I have met the same question

**Comment by lgffllsxx** [comment]
Maybe I can share a suggestion. When calling `rknn.init_runtime()`, the target parameter is mainly used for remote debugging via `ADB`.
If that doesn’t work in your case, you could try running it directly on the RK3588. In that case, you don’t need to provide the `target` or `device_id` parameters.
You can also optionally specify `core_mask=RKNNLite.NPU_CORE_AUTO` to choose which NPU core to use.
I ran into a similar issue when using `rknn_lite`, and this approach worked for me — hopefully it helps you as well.

**Comment by xinmou0129** [comment]
> Maybe I can share a suggestion. When calling `rknn.init_runtime()`, the target parameter is mainly used for remote debugging via `ADB`. If that doesn’t work in your case, you could try running it directly on the RK3588. In that case, you don’t need to provide the `target` or `device_id` parameters. You can also optionally specify `core_mask=RKNNLite.NPU_CORE_AUTO` to choose which NPU core to use. I ran into a similar issue when using `rknn_lite`, and this approach worked for me — hopefully it helps you as well.

Thank you!
