### ISSUE TITLE
Error convert yolov8 !

### ISSUE THREAD

**Issue by lktinh2018** [airockchip/rknn_model_zoo#25]
Hello author,

I can convert to yolov5 but got following error with yolov8.
Could you please help me?

E Catch exception when building RKNN model!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/RKNNnetbuilder.py", line 486, in rknn.base.RKNNlib.RKNNnetbuilder.RKNNNetBuilder.build_layer
E   File "rknn/base/RKNNlib/layer/RKNNlayer.py", line 293, in rknn.base.RKNNlib.layer.RKNNlayer.RKNNLayer.compute_tensor
E   File "rknn/base/RKNNlib/layer/divlayer.py", line 35, in rknn.base.RKNNlib.layer.divlayer.DivLayer.compute_out_tensor
E   File "/home/nexroot/Data/Virtual_Envs/env_rknn/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
E     raise e.with_traceback(filtered_tb) from None
E   File "/home/nexroot/Data/Virtual_Envs/env_rknn/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1517, in _truediv_python3
E     raise TypeError(f"`x` and `y` must have the same dtype, "
E TypeError: `x` and `y` must have the same dtype, got tf.float32 != tf.int32.
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
---> Export RKNN model
E RKNN model data is None, please load model first!
E RKNN model data is None, please load model first!
  WARNING: simulator does not support exporting pre_compiled model. Ignore!
Convert Done!

**Comment by marco0913** [comment]
Hi were you able to convert to yolov8 at the end?
