### ISSUE TITLE
使用convert_yolo_ppyolo.sh转换yolov5时遇到问题

### ISSUE THREAD

**Issue by Shifiter** [airockchip/rknn_model_zoo#28]
利用airockship提供的yolov5训练（[https://github.com/airockchip/yolov5），利用其中的python export.py --rknpu RK3588转换得到onnx，尝试运行convert_yolo_ppyolo.sh时遇到问题，yolo_ppyolo.yaml配置如下：
#support yolo[v5,v6,v7,v8], ppyoloe_plus
model_framework: pytorch
model_file_path: ./PPE4_best.pt
RK_device_platform: RK3588
RK_device_id: simulator
dataset: ../../../../../datasets/PPE/PPE_dataset.txt
quantize: True
# pre_compile: online

graph:
  in_0:
    shape: 3,640,640
    mean_values: 0
    std_values: 255
    img_type: RGB

configs:
  quantized_dtype: asymmetric_quantized-8
  quantized_algorithm: normal
  optimization_level: 3
==================
运行日志如下：
raceback (most recent call last):
  File "../../../../../common/rknn_converter/rknn_convert.py", line 14, in <module>
    from phase import convert_phase, validate_phase
  File "/home/ubuntu/PCHuang/rknn_model_zoo-main/common/rknn_converter/phase.py", line 20, in <module>
    from capi_simply_excuter.commond_excuter.toolkit1_capi import tk1_capi_excuter
  File "/home/ubuntu/PCHuang/rknn_model_zoo-main/common/capi_simply_excuter/commond_excuter/toolkit1_capi.py", line 10, in <module>
    binary_dir = '/{}/capi_tools/toolkit1/rknn_capi_test/install'.format(_sep.join(realpath[: realpath.index('rknn_model_zoo')+1]))
ValueError: 'rknn_model_zoo' is not in list

**Comment by lihualilee** [comment]
我也碰到这个问题了，请问您解决了么？

**Comment by mmastererliu** [comment]
您好  这个问题您怎么解决的

**Comment by Sicily-love** [comment]
@mmastererliu @Shifiter you can try to rename folder name from rknn_model_zoo-main to rknn_model_zoo,it works for me

**Comment by CompliceU** [comment]
---> Export RKNN model
  WARNING: RK3588 model needn't pre_compile. Ignore!
Convert Done!
/bin/sh: 1: adb: not found
/bin/sh: 1: adb: not found
/bin/sh: 1: adb: not found
/bin/sh: 1: adb: not found
Traceback (most recent call last):
  File "../../../../../common/rknn_converter/rknn_convert.py", line 79, in <module>
    convert(config_dict, args)
  File "../../../../../common/rknn_converter/rknn_convert.py", line 24, in convert
    vp = validate_phase(rknn, model_config_dict, args)
  File "/home/puppy/yl/OBJ_plane/rknn_model_zoo/common/rknn_converter/phase.py", line 192, in __init__
    self.check_board_info()
  File "/home/puppy/yl/OBJ_plane/rknn_model_zoo/common/rknn_converter/phase.py", line 535, in check_board_info
    self._smart_record('librknn_runtime_version', "{}".format(bc.get_librknn_version()))
  File "/home/puppy/yl/OBJ_plane/rknn_model_zoo/common/utils/board_checker.py", line 81, in get_librknn_version
    _result = result[0].rstrip('\n').split('version: ')[1]
IndexError: list index out of range

@Shifiter @mmastererliu @Sicily-love  你好，我这个是不是意味着模型已经转成功了，但是由于没有找到3588这个设备所以测试没成功呀，大佬

**Comment by Sicily-love** [comment]
@CompliceU You can try my method and see if it works, and you can also use "adb devices" to check if the device is connected.
