### ISSUE TITLE
ModuleNotFoundError: No module named 'rknn'

### ISSUE THREAD

**Issue by jia0511** [airockchip/rknn_model_zoo#40]
python common/rknn_converter/rknn_convert.py --yml_path ./yolo_ppyolo.yml --python_api_test --capi_test

Traceback (most recent call last):
  File "/home/ubuntu/data1/rockchip/rknn_model_zoo/common/rknn_converter/rknn_convert.py", line 14, in <module>
    from phase import convert_phase, validate_phase
  File "/home/ubuntu/data1/rockchip/rknn_model_zoo/common/rknn_converter/phase.py", line 8, in <module>
    from rknn.api import RKNN
ModuleNotFoundError: No module named 'rknn'

**Comment by airockchip** [comment]
Please install rknn-toolkit(https://github.com/rockchip-linux/rknn-toolkit) / rknn-toolkit2(https://github.com/rockchip-linux/rknn-toolkit2) first.
Chips suitable for rknn toolkit include: RK1806, RK1808, RK3399Pro, RV1109, RV1126
Chips suitable for rknn toolkit2 include: RK3566, RK3568, RK3588, RK3588S, RV1103, RV1106, RK3562
