### ISSUE TITLE
YOLOv8 | Error with the post-processing part

### ISSUE THREAD

**Issue by asmaamirkhan** [airockchip/rknn_model_zoo#44]
Hello,

I'm trying to set up **YOLOv8n** on my RK1808 device. I followed the steps in your [YOLOv8 repository](https://github.com/airockchip/ultralytics_yolov8) to create a .torchscript file. Then, I used your [RKNN convert script](https://github.com/airockchip/rknn_model_zoo/blob/main/common/rknn_converter/rknn_convert.py) to make a .rknn file, and that part worked fine.

But, when I run the evaluation script, the script is failing in the post-processing part. The error is like the following for the .torchscript model:
```bash
Model-/MODEL_PATH/yolov8n.torchscript is pytorch model, starting val
INFERENCE TIME: 0.26699399948120117
Traceback (most recent call last):
  File "yolo_map_test_rknn.py", line 430, in <module>
    boxes, classes, scores = post_process(outputs, anchors, args)
  File "yolo_map_test_rknn.py", line 202, in post_process
    input_data[pair_per_branch*i], None, args))
  File "yolo_map_test_rknn.py", line 128, in box_process
    grid_h, grid_w = position.shape[2:4]
ValueError: not enough values to unpack (expected 2, got 1)
```
The error is like the following for the .rknn model:

```bash
Model-/MODEL_PATH/RK1808_3399pro/yolov8n_RK1808_3399pro_u8.rknn is rknn model, starting val
INFERENCE TIME: 0.0664527416229248
Traceback (most recent call last):
  File "yolo_map_test_rknn.py", line 430, in <module>
    boxes, classes, scores = post_process(outputs, anchors, args)
  File "yolo_map_test_rknn.py", line 202, in post_process
    input_data[pair_per_branch*i], None, args))
  File "yolo_map_test_rknn.py", line 128, in box_process
    grid_h, grid_w = position.shape[2:4]
ValueError: not enough values to unpack (expected 2, got 1)
```

I noticed that the output has a shape of (1, 84, 8400), but the code we have expects it to have four dimensions.

Do you have any ideas on how to fix this problem with processing the output for YOLOv8?

Thank you in advance!

**Comment by TetVoid** [comment]
Hi, I have the similar issue according post-processing stage. I don't really understand the dimensions of output vector. I use RC3588s, OS Debian 12, toolkit version for Python 3.10. Do you have any ideas about solving this problem? What is the real output shape and output format in general for YOLOv8n?

shape of yolov8n output (1, 1, 84, 8400, 1)

Traceback (most recent call last):
  File "/home/orangepi/Desktop/CvPepoleDetector/rknn_model_zoo/models/CV/object_detection/yolo/RKNN_python_demo/yolo_map_test_rknn.py", line 386, in <module>
    boxes, classes, scores = post_process(outputs, s.anchors, args)
  File "/home/orangepi/Desktop/CvPepoleDetector/rknn_model_zoo/models/CV/object_detection/yolo/RKNN_python_demo/yolo_map_test_rknn.py", line 186, in post_process
    classes_conf.append(input_data[pair_per_branch*i+1])
IndexError: list index out of range

**Comment by asmaamirkhan** [comment]
Hi @TetVoid,
 
I'm not sure but this issue might be useful #46

**Comment by 17839776642** [comment]
Export the _rknnopt.torchscript model using the following code.
from ultralytics import YOLO

model = YOLO('D:/Desktop/runs/detect/train/weights/best.pt')
path = model.export(format='rknn')

**Comment by 17839776642** [comment]
> 嗨，根据后处理阶段，我遇到了类似的问题。我真的不了解输出向量的维度。我使用 RC3588s、OS Debian 12、Python 3.10 工具包版本。你对解决这个问题有什么想法吗？YOLOv8n 的实际输出形状和输出格式一般是什么？
> 
> Yolov8N 输出的形状（1、1、84、8400、1）
> 
> 回溯（最近一次调用最后一次）： 文件“/home/orangepi/Desktop/CvPepoleDetector/rknn_model_zoo/models/CV/object_detection/yolo/RKNN_python_demo/yolo_map_test_rknn.py”，第 386 行，在框中，类，分数 = post_process（outputs， s.anchors， args） 文件“/home/orangepi/Desktop/CvPepoleDetector/rknn_model_zoo/models/CV/object_detection/yolo/RKNN_python_demo/yolo_map_test_rknn.py”， 第 186 行，在 post_process classes_conf.append（input_data[pair_per_branch*i+1]） IndexError：列表索引超出范围

Export the _rknnopt.torchscript model using the following code.
from ultralytics import YOLO

model = YOLO('D:/Desktop/runs/detect/train/weights/best.pt')
path = model.export(format='rknn')

**Comment by apanand14** [comment]
> Hello,
> 
> I'm trying to set up **YOLOv8n** on my RK1808 device. I followed the steps in your [YOLOv8 repository](https://github.com/airockchip/ultralytics_yolov8) to create a .torchscript file. Then, I used your [RKNN convert script](https://github.com/airockchip/rknn_model_zoo/blob/main/common/rknn_converter/rknn_convert.py) to make a .rknn file, and that part worked fine.
> 
> But, when I run the evaluation script, the script is failing in the post-processing part. The error is like the following for the .torchscript model:
> 
> ```shell
> Model-/MODEL_PATH/yolov8n.torchscript is pytorch model, starting val
> INFERENCE TIME: 0.26699399948120117
> Traceback (most recent call last):
>   File "yolo_map_test_rknn.py", line 430, in <module>
>     boxes, classes, scores = post_process(outputs, anchors, args)
>   File "yolo_map_test_rknn.py", line 202, in post_process
>     input_data[pair_per_branch*i], None, args))
>   File "yolo_map_test_rknn.py", line 128, in box_process
>     grid_h, grid_w = position.shape[2:4]
> ValueError: not enough values to unpack (expected 2, got 1)
> ```
> 
> The error is like the following for the .rknn model:
> 
> ```shell
> Model-/MODEL_PATH/RK1808_3399pro/yolov8n_RK1808_3399pro_u8.rknn is rknn model, starting val
> INFERENCE TIME: 0.0664527416229248
> Traceback (most recent call last):
>   File "yolo_map_test_rknn.py", line 430, in <module>
>     boxes, classes, scores = post_process(outputs, anchors, args)
>   File "yolo_map_test_rknn.py", line 202, in post_process
>     input_data[pair_per_branch*i], None, args))
>   File "yolo_map_test_rknn.py", line 128, in box_process
>     grid_h, grid_w = position.shape[2:4]
> ValueError: not enough values to unpack (expected 2, got 1)
> ```
> 
> I noticed that the output has a shape of (1, 84, 8400), but the code we have expects it to have four dimensions.
> 
> Do you have any ideas on how to fix this problem with processing the output for YOLOv8?
> 
> Thank you in advance!

Hey, did you solve the issue? I have simillar one at the moment with onnx model.

**Comment by Starkguava** [comment]
My YOLOv5 output is similar to yours, which is a 1x25200x(n+5) array. I modified some code in the ONNX to RKNN demo in Python and ran it successfully, but I'm not very familiar with Android java and C++, so I don't know how to modify it, and I haven't managed to run it on the board yet. 

```python
def process(output, obj_thresh, nms_thresh):
    output = output[0]  # (25200, 19)

    box_confidence = output[:, 4]  # confidence
    box_class_probs = output[:, 5:]  # class

    # thresh
    mask = box_confidence >= obj_thresh
    filtered_boxes = output[mask]

    if filtered_boxes.size == 0:
        return [], [], []

    # center to left,top
    boxes = filtered_boxes[:, :4]
    boxes[:, :2] = boxes[:, :2] - (boxes[:, 2:] / 2) 

    confidences = filtered_boxes[:, 4]
    class_probs = filtered_boxes[:, 5:] 

    class_ids = np.argmax(class_probs, axis=1)
    class_scores = class_probs[np.arange(len(class_probs)), class_ids]

    scores = confidences * class_scores
    mask = scores >= obj_thresh
    boxes = boxes[mask]
    scores = scores[mask]
    class_ids = class_ids[mask]

    # NMS
    nms_indices = nms_boxes(boxes, scores, nms_thresh)

    return boxes[nms_indices], class_ids[nms_indices], scores[nms_indices]


def filter_boxes(boxes, box_confidences, box_class_probs):
    """Filter boxes with box threshold. It's a bit different with origin yolov5 post process!

    # Arguments
        boxes: ndarray, boxes of objects.
        box_confidences: ndarray, confidences of objects.
        box_class_probs: ndarray, class_probs of objects.

    # Returns
        boxes: ndarray, filtered boxes.
        classes: ndarray, classes for boxes.
        scores: ndarray, scores for boxes.
    """
    boxes = boxes.reshape(-1, 4)
    box_confidences = box_confidences.reshape(-1)
    box_class_probs = box_class_probs.reshape(-1, box_class_probs.shape[-1])

    _box_pos = np.where(box_confidences >= OBJ_THRESH)
    boxes = boxes[_box_pos]
    box_confidences = box_confidences[_box_pos]
    box_class_probs = box_class_probs[_box_pos]

    class_max_score = np.max(box_class_probs, axis=-1)
    classes = np.argmax(box_class_probs, axis=-1)
    _class_pos = np.where(class_max_score >= OBJ_THRESH)

    boxes = boxes[_class_pos]
    classes = classes[_class_pos]
    scores = (class_max_score * box_confidences)[_class_pos]

    return boxes, classes, scores


def nms_boxes(boxes, scores, nms_thresh):
    x = boxes[:, 0]
    y = boxes[:, 1]
    w = boxes[:, 2]
    h = boxes[:, 3]

    areas = w * h
    order = scores.argsort()[::-1]

    keep = []
    while order.size > 0:
        i = order[0]
        keep.append(i)

        xx1 = np.maximum(x[i], x[order[1:]])
        yy1 = np.maximum(y[i], y[order[1:]])
        xx2 = np.minimum(x[i] + w[i], x[order[1:]] + w[order[1:]])
        yy2 = np.minimum(y[i] + h[i], y[order[1:]] + h[order[1:]])

        w1 = np.maximum(0.0, xx2 - xx1 + 0.00001)
        h1 = np.maximum(0.0, yy2 - yy1 + 0.00001)
        inter = w1 * h1

        ovr = inter / (areas[i] + areas[order[1:]] - inter)
        inds = np.where(ovr <= nms_thresh)[0]
        order = order[inds + 1]
    keep = np.array(keep)
    return keep


def yolov5_post_process(input_data, obj_thresh, nms_thresh):
    boxes, classes, scores = process(input_data, obj_thresh, nms_thresh)
    return boxes, classes, scores


def draw(image, boxes, scores, classes):
    """Draw the boxes on the image.

    # Argument:
        image: original image.
        boxes: ndarray, boxes of objects.
        classes: ndarray, classes of objects.
        scores: ndarray, scores of objects.
        all_classes: all classes name.
    """
    print("{:^12} {:^12}  {}".format('class', 'score', 'xmin, ymin, xmax, ymax'))
    print('-' * 50)
    for box, score, cl in zip(boxes, scores, classes):
        top, left, width, heigh = box
        top = int(top)
        left = int(left)
        right = int(top + width)
        bottom = int(left + heigh)

        cv2.rectangle(image, (top, left), (right, bottom), (255, 0, 0), 2)
        cv2.putText(image, '{0} {1:.2f}'.format(CLASSES[cl], score),
                    (top, left - 6),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.6, (0, 0, 255), 2)

        print("{:^12} {:^12.3f} [{:>4}, {:>4}, {:>4}, {:>4}]".format(CLASSES[cl], score, top, left, right, bottom))


def letterbox(im, new_shape=(640, 640), color=(0, 0, 0)):
    # Resize and pad image while meeting stride-multiple constraints
    shape = im.shape[:2]  # current shape [height, width]
    if isinstance(new_shape, int):
        new_shape = (new_shape, new_shape)

    # Scale ratio (new / old)
    r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])

    # Compute padding
    ratio = r, r  # width, height ratios
    new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
    dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding

    dw /= 2  # divide padding into 2 sides
    dh /= 2

    if shape[::-1] != new_unpad:  # resize
        im = cv2.resize(im, new_unpad, interpolation=cv2.INTER_LINEAR)
    top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
    left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
    im = cv2.copyMakeBorder(im, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)  # add border
    return im, ratio, (dw, dh)


def export():
    # Create RKNN object
    rknn = RKNN(verbose=True)

    # pre-process config
    print('--> Config model')
    rknn.config(mean_values=[[0, 0, 0]], std_values=[[255, 255, 255]], target_platform='rk3588')
    print('done')

    # Load ONNX model
    print('--> Loading model')
    ret = rknn.load_onnx(model=ONNX_MODEL)
    if ret != 0:
        print('Load model failed!')
        exit(ret)
    print('done')

    # Build model
    print('--> Building model')
    ret = rknn.build(do_quantization=QUANTIZE_ON, dataset=DATASET)
    if ret != 0:
        print('Build model failed!')
        exit(ret)
    print('done')

    # Export RKNN model
    print('--> Export rknn model')
    ret = rknn.export_rknn(RKNN_MODEL)
    if ret != 0:
        print('Export rknn model failed!')
        exit(ret)
    print('done')

    # Init runtime environment
    print('--> Init runtime environment')
    ret = rknn.init_runtime()
    if ret != 0:
        print('Init runtime environment failed!')
        exit(ret)
    print('done')

    # Set inputs
    img = cv2.imread(IMG_PATH)
    # img, ratio, (dw, dh) = letterbox(img, new_shape=(IMG_SIZE, IMG_SIZE))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

    # Inference
    print('--> Running model')
    img2 = np.expand_dims(img, 0)
    outputs = rknn.inference(inputs=[img2])
    print(outputs)
    boxes, classes, scores = yolov5_post_process(outputs[0], OBJ_THRESH, NMS_THRESH)

    img_1 = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    if boxes is not None:
        draw(img_1, boxes, scores, classes)
        cv2.imwrite('result.jpg', img_1)
        print('Save results to result.jpg!')

    rknn.release()


if __name__ == '__main__':
    export()

**Comment by Starkguava** [comment]
https://doc.embedfire.com/linux/rk356x/Ai/zh/latest/lubancat_ai/example/yolov8.html
