### ISSUE TITLE
关于模型转换中平台填写rk3399pro不支持问题的解决

### ISSUE THREAD

**Issue by HeinzGong** [airockchip/rknn_model_zoo#6]
如果在转换yml中平台填写rk3399pro，
那么在config_parser.py中由于
`self.RK_device_platform = project_config.get('RK_device_platform', 'RK1808').upper()`
将“rk3399pro”大写为“RK3399PRO”
而默认字典是
```
NPU_VERSION_1_DEVICES = ['RK3399pro', 'RK1808', 'RV1109', 'RV1126']
NPU_VERSION_2_DEVICES = ['RK3566', 'RK3568', 'RK3588']
```
导致输出
```
Traceback (most recent call last):
  File "../../../../../common/rknn_converter/rknn_convert.py", line 171, in <module>
    parser.parse()
  File "D:\DL_Model\yolov5\rknn_model_zoo\common\rknn_converter\config_parser.py", line 359, in parse
    self.parse_hyper_config()
  File "D:\DL_Model\yolov5\rknn_model_zoo\common\rknn_converter\config_parser.py", line 50, in parse_hyper_config
    assert False, "{} devices is not support. Now support devices list - {}".format(RK_device_platform, NPU_VERSION_2_DEVICES+ NPU_VERSION_1_DEVICES)
AssertionError: RK3399PRO devices is not support. Now support devices list - ['RK3566', 'RK3568', 'RK3588', 'RK3399pro', 'RK1808', 'RV1109', 'RV1126']
```
希望官方能修改，避免后续开发人员遇到此问题

**Comment by zen-xingle** [comment]
谢谢反馈。已修复，将关闭这个问题。
