### ISSUE TITLE
Yolov8 conversion on Ubuntu 22.04 host machine for RK3399PRO Board

### ISSUE THREAD

**Issue by trohit920** [airockchip/rknn_model_zoo#62]
I and ollowing this repo to install RKNN-Toolkit on host PC to convert YOLO-V8 Model to RKNN format and deploy on RK3399PRO board. However, I encountered below error while doing so,

```
WARNING - 'configs' in yaml file is deprecate, rename it as 'config'
W rknn-toolkit version: 1.7.5
WARNING - rknn.api import failed, skip rknn_config_check
========== parser_config ==========
TOOLKIT_MAIN_VERSION: 1
RK_device_platform: RK3399PRO
model_framework: pytorch
verbose: False
quantize: True
dataset: ../../../../../datasets/COCO/coco_subset_10.txt
graph:
  in_0:
    shape: 1,3,640,640
    mean_values: 0
    std_values: 255
    img_type: RGB
config:
  quantized_dtype: asymmetric_affine-u8
  target_platform: RK3399PRO
  quantized_algorithm: normal
  optimization_level: 3
  mean_values: [[0, 0, 0]]
  std_values: [[255, 255, 255]]
  reorder_channel: 0 1 2
pre_compile: online
core_mask: 1
export_rknn:
  export_path: ./model_cvt/RK1808_3399pro/yolov8n_rknnopt_RK1808_3399pro_u8.rknn
model_file_path: yolov8n_rknnopt.torchscript
build:
  do_quantization: True
  dataset: ./../../../../../datasets/COCO/coco_subset_10.txt
qnnpack: False
load:
  model: ./yolov8n_rknnopt.torchscript
  input_size_list: [[3, 640, 640]]
inputs:
  in_0:
    shape: [1, 3, 640, 640]
    mean_values: [0, 0, 0]
    std_values: [255, 255, 255]
    img_type: RGB
outputs:
input_example: [{'in_0': '../../../../../datasets/COCO/val_test/000000000285.jpg'}, {'in_0': '../../  ...
export_pre_compile_path: ./model_cvt/RK1808_3399pro/yolov8n_rknnopt_RK1808_3399pro_u8_precompile.rknn
===================================
---> Create RKNN object
W rknn-toolkit version: 1.7.5
---> Seting RKNN config
---> Loading pytorch model
Traceback (most recent call last):
  File "../../../../../common/rknn_converter/rknn_convert.py", line 99, in <module>
    convert(config_dict, args)
  File "../../../../../common/rknn_converter/rknn_convert.py", line 19, in convert
    rknn = cp.convert()
  File "/home/fazliddin/rock_chip/rknn_model_zoo/common/rknn_converter/phase.py", line 122, in convert
    load_function(**model_config_dict['load'])
  File "/home/fazliddin/.conda/envs/rk3399pro/lib/python3.8/site-packages/rknn/api/rknn.py", line 227, in load_pytorch
    ret = self.rknn_base.load_pytorch(model, input_size_list, inputs, outputs, convert_engine)
  File "rknn/api/rknn_base.py", line 439, in rknn.api.rknn_base.RKNNBase.load_pytorch
  File "/home/fazliddin/.conda/envs/rk3399pro/lib/python3.8/site-packages/rknn/base/acuitylib/__init__.py", line 1, in <module>
    from acuitylib.optimize.optimizer import Optimizer
  File "rknn/base/acuitylib/optimize/optimizer.py", line 9, in init rknn.base.acuitylib.optimize.optimizer
  File "/home/fazliddin/.conda/envs/rk3399pro/lib/python3.8/site-packages/rknn/base/acuitylib/__init__.py", line 1, in <module>
    from acuitylib.optimize.optimizer import Optimizer
ImportError: cannot import name 'Optimizer' from partially initialized module 'acuitylib.optimize.optimizer' (most likely due to a circular import) (/home/fazliddin/.conda/envs/rk3399pro/lib/python3.8/site-packages/rknn/base/acuitylib/optimize/optimizer.cpython-38-x86_64-linux-gnu.so)
```
Can you please help me with this?

**Comment by kaisawind** [comment]
```bash
pip uninstall torch
pip install tensorflow==2.2.0
pip install torch==1.10.0
```
