### ISSUE TITLE
RK3588连板推理报错

### ISSUE THREAD

**Issue by rzzhangtao** [airockchip/rknn_model_zoo#63]
使用rknn-toolkit2 1.6.0版本进行python API连板推理验证，报错信息如下所示，但实际上通过adb devices可以查看到设备，也可以通过adb shell进入到设备。请问可以如何解决：

python yolov5.py --model_path ../model/yolov5s_relu.rknn --target rk3588 --img_save
use anchors from '../model/anchors_yolov5.txt', which is [[[10.0, 13.0], [16.0, 30.0], [33.0, 23.0]], [[30.0, 61.0], [62.0, 45.0], [59.0, 119.0]], [[116.0, 90.0], [156.0, 198.0], [373.0, 326.0]]]
W __init__: rknn-toolkit2 version: 1.6.0+81f21f4d
--> Init runtime environment
**error: cannot bind listener: attempted to listen on unavailable socket type: 'localabstract:transfer_proxy'**
**E init_runtime: Connect to Device Failure (-2), Please check the USB connection!**
E init_runtime: Catch exception when init runtime!
E init_runtime: Traceback (most recent call last):
E init_runtime:   File "rknn/api/rknn_base.py", line 2492, in rknn.api.rknn_base.RKNNBase.init_runtime
E init_runtime:   File "rknn/api/rknn_runtime.py", line 216, in rknn.api.rknn_runtime.RKNNRuntime.__init__
E init_runtime:   File "rknn/api/rknn_platform.py", line 352, in rknn.api.rknn_platform.start_ntp_or_adb
E init_runtime: Exception: Init runtime environment failed!
W If you can't handle this error, please try updating to the latest version of the toolkit2 and runtime from:
  https://console.zbox.filez.com/l/I00fc3 (Pwd: rknn)  Path: RKNPU2_SDK / 1.X.X / develop /
  If the error still exists in the latest version, please collect the corresponding error logs and the model,
  convert script, and input data that can reproduce the problem, and then submit an issue on:
  https://redmine.rock-chips.com (Please consult our sales or FAE for the redmine account)
Init runtime environment failed

**Comment by Suqier** [comment]
请问这个问题现有解决办法了吗？

**Comment by cugdom** [comment]
报错最后一句提示的意思：在板子上更新并执行rcnn_server

**Comment by Suqier** [comment]
好的，感谢
