### ISSUE TITLE
使用1.5版本的rknn_model_zoo转onnx到rknn报错

### ISSUE THREAD

**Issue by Newcomer-CL** [airockchip/rknn_model_zoo#65]
Traceback (most recent call last):
  File "../../../../../common/rknn_converter/rknn_convert.py", line 99, in <module>
    convert(config_dict, args)
  File "../../../../../common/rknn_converter/rknn_convert.py", line 19, in convert
    rknn = cp.convert()
  File "/home/wjn/RKNN1808/rknn_model_zoo/common/rknn_converter/phase.py", line 122, in convert
    load_function(**model_config_dict['load'])
  File "/home/wjn/miniconda3/envs/rr/lib/python3.8/site-packages/rknn/api/rknn.py", line 150, in load_onnx
    ret = self.rknn_base.load_onnx(model, inputs, input_size_list, outputs)
  File "rknn/api/rknn_base.py", line 309, in rknn.api.rknn_base.RKNNBase.load_onnx
  File "/home/wjn/miniconda3/envs/rr/lib/python3.8/site-packages/rknn/base/acuitylib/__init__.py", line 1, in <module>
    from acuitylib.optimize.optimizer import Optimizer
  File "rknn/base/acuitylib/optimize/optimizer.py", line 9, in init rknn.base.acuitylib.optimize.optimizer
  File "/home/wjn/miniconda3/envs/rr/lib/python3.8/site-packages/rknn/base/acuitylib/__init__.py", line 1, in <module>
    from acuitylib.optimize.optimizer import Optimizer
ImportError: cannot import name 'Optimizer' from partially initialized module 'acuitylib.optimize.optimizer' (most likely due to a circular import) (/home/wjn/miniconda3/envs/rr/lib/python3.8/site-packages/rknn/base/acuitylib/optimize/optimizer.cpython-38-x86_64-linux-gnu.so)

就是这个from acuitylib.optimize.optimizer import Optimizer 没有
Optimizer

**Comment by Newcomer-CL** [comment]
使用的转换脚本时1.5版本下的rknn_model_zoo/models/CV/object_detection/yolo/RKNN_model_convert/convert_yolo.sh
