### ISSUE TITLE
Using rknn_model_zoo on ARM

### ISSUE THREAD

**Issue by Vdol22** [airockchip/rknn_model_zoo#90]
Hi! My team tries to run your model zoo on an Edge2 ARM rk3588S device. Export of a model has been successfully conducted on a different x64 Linux PC, yet while to run inference on Edge2 there's an error. Inference code:

```
def load_and_resize_images(folder_path, target_size=(640, 640)):
    image_batch = []
    for filename in os.listdir(folder_path):
        img_path = os.path.join(folder_path, filename)
        img = cv2.imread(img_path)
        if img is not None:
            img = cv2.resize(img, target_size)
            image_batch.append(img)
    return image_batch

def main():
    batch_size = 1
    RK3588_RKNN_MODEL = './yolo-models/new_yolov8m_seg.rknn'
    dataset_folder = './dataset'

    rknn_model = RK3588_RKNN_MODEL
    rknn_lite = RKNNLite()
    print('--> Load RKNN model')
    ret = rknn_lite.load_rknn(rknn_model)
    if ret != 0:
        print('Load RKNN model failed')
        exit(ret)
    print('done')
    ret = rknn_lite.init_runtime(core_mask=RKNNLite.NPU_CORE_0)
    if ret != 0:
        print('Init runtime environment failed')
        exit(ret)
    print('done')

    time_delta_list = []
    outputs = []

    image_batch = load_and_resize_images(dataset_folder)

    pbar = tqdm.tqdm(range(0, len(image_batch), batch_size))
    for i in pbar:
        batch_images = image_batch[i:i+batch_size]
        time_1 = time.time()
        outputs = rknn_lite.inference(inputs=batch_images)
        time_2 = time.time()
        time_delta_list.extend(
            [(time_2 - time_1) / batch_size] * batch_size
        )
        outputs.append(outputs)
    print(outputs[0])
    print(outputs[0].shape)
    print(len(outputs))
    print(len(time_delta_list))
    print(sum(time_delta_list) / len(time_delta_list))

if __name__ == "__main__":
    main()
```
error message:
```
--> Load RKNN model
done
I RKNN: [05:19:24.307] RKNN Runtime Information, librknnrt version: 1.6.0 (9a7b5d24c@2023-12-13T17:31:11)
I RKNN: [05:19:24.307] RKNN Driver Information, version: 0.9.3
I RKNN: [05:19:24.307] RKNN Model Information, version: 6, toolkit version: 2.0.0b0+9bab5682(compiler version: 2.0.0b0 (35a6907d79@2024-03-24T02:34:11)), target: RKNPU v2, target platform: rk3588, framework name: ONNX, framework layout: NCHW, model inference type: static_shape
W RKNN: [05:19:24.307] RKNN Model version: 2.0.0 not match with rknn runtime version: 1.6.0
W RKNN: [05:19:24.353] query RKNN_QUERY_INPUT_DYNAMIC_RANGE error, rknn model is static shape type, please export rknn with dynamic_shapes
done
W Query dynamic range failed. Ret code: RKNN_ERR_MODEL_INVALID. (If it is a static shape RKNN model, please ignore the above warning message.)
  0%|          | 0/1 [00:00<?, ?it/s]E Catch exception when setting inputs.
E Traceback (most recent call last):
  File "/home/khadas/miniconda3/envs/rknn/lib/python3.10/site-packages/rknnlite/api/rknn_lite.py", line 200, in inference
    self.rknn_runtime.set_inputs(inputs, data_type, data_format, inputs_pass_through=inputs_pass_through)
  File "rknnlite/api/rknn_runtime.py", line 1067, in rknnlite.api.rknn_runtime.RKNNRuntime.set_inputs
Exception: The input[0] need 4dims input, but 3dims input buffer feed.

  0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/khadas/bg-eraser/bg-eraser/rknn-yolo-benchmark.py", line 62, in <module>
    main()
  File "/home/khadas/bg-eraser/bg-eraser/rknn-yolo-benchmark.py", line 54, in main
    outputs.append(outputs)
AttributeError: 'NoneType' object has no attribute 'append'
```

we use rknn-lite2 v1.6.0 if it matters. Please help, we need to get .jpg binarised masks from yolo8m-seg inference as a result.

**Comment by Vdol22** [comment]
@zen-xingle kindly ask you to answer! Is there a way to make additional training of the existing .onnx yolov8-seg models (that won't break their ability to convert to .rknn) and could you upload yolov8l-seg and x-seg .onnx versions into the zoo?
