### ISSUE TITLE
rv1126上任何模型在1.7.5版本上都会提示E Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID

### ISSUE THREAD

**Issue by kingzcheung** [airockchip/rknn_model_zoo#99]
## yolov5
python convert.py /home/nianqing/try/anitnet-export/exp12/weights/best.onnx rv1126 u8
转换成功，加载失败
python yolov5.py --model_path ../model/yolov5.rknn --target rv1126 --device_id b9467c6be2237e7a
```
use anchors from '../model/anchors_yolov5.txt', which is [[[10.0, 13.0], [16.0, 30.0], [33.0, 23.0]], [[30.0, 61.0], [62.0, 45.0], [59.0, 119.0]], [[116.0, 90.0], [156.0, 198.0], [373.0, 326.0]]]
W rknn-toolkit version: 1.7.5
--> Init runtime environment
I NPUTransfer: Starting NPU Transfer Client, Transfer version 2.1.0 (b5861e7@2020-11-23T11:50:36)
E RKNNAPI: rknn_init,  msg_load_ack fail, ack = 1(ACK_FAIL), expect 0(ACK_SUCC)!
E RKNNAPI: ==============================================
E RKNNAPI: RKNN VERSION:
E RKNNAPI:   API: 1.7.5 (bb79b30 build: 2023-06-20 09:54:19)
E RKNNAPI:   DRV: 1.7.5 (bb79b30 build: 2023-07-18 10:53:10)
E RKNNAPI: ==============================================
E Catch exception when init runtime!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 1008, in rknn.api.rknn_base.RKNNBase.init_runtime
E   File "rknn/api/rknn_runtime.py", line 340, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
E Exception: RKNN init failed. error code: RKNN_ERR_MODEL_INVALID
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
E Current device id is: b9467c6be2237e7a
E Devices connected:
E ['b9467c6be2237e7a']
Init runtime environment failed
```
## mobilenetv2
mobilenetv2 我试了两个版本，一个是自己的版本，一个是官方提供的版本，也是一样的问题，转换可以成功，但是连接到板子上出现上面类似的错误：
[log.txt](https://github.com/airockchip/rknn_model_zoo/files/14917079/log.txt)

**Comment by wangjl1993** [comment]
我也碰到了，请问下解决了么？
